  - name: Levantar localstack
    hosts: localhost
    gather_facts: no
    vars_files: variables.yml
    environment:
      # SERVICES: 'iam,lambda,dynamodb,apigateway,s3,sns,kinesis'
      DEFAULT_REGION: 'us-west-2'
      LAMBDA_EXECUTOR: "{{ ls_lambda_executor }}"
      LAMBDA_REMOTE_DOCKER: "{{ ls_lambda_remote_docker }}" 
      DATA_DIR: "{{ ls_data_dir }}"
    tasks:
      - name: Tear down existing services
        docker_compose:
          project_src: "{{ ls_docker_dir }}"
          state: absent

      - name: Create and start services
        docker_compose:
          project_src: "{{ ls_docker_dir }}"
        register: output

      - debug:
          var: output

      - name: Run `docker-compose up` again
        docker_compose:
          project_src: "{{ ls_docker_dir }}"
          build: no
        register: output

      - debug:
          var: output